# Generated by Django 4.2.28 on 2026-03-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_seller_sellerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
