# Generated by Django 4.2.28 on 2026-03-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_payment_review_coupon_order_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, help_text='Legacy admin notes field', null=True),
        ),
    ]
